#!/usr/bin/env python3

import asyncio
import asyncdns
import sys

def main(args):
    resolver = asyncdns.MulticastResolver()
    loop = asyncio.get_event_loop()

    query = asyncdns.Query(args[1], asyncdns.ANY, asyncdns.IN)
    f = resolver.lookup(query)

    loop.run_until_complete(f)

    print(f.result())

if __name__ == '__main__':
    main(sys.argv)
